language: node_js
sudo: false
node_js:
  - "node"
  - "lts/*"
  - "8"
  - "6"
env:
	- "RUN_IN_PARENT=true"
	- "RUN_IN_PARENT=false"
addons:
  chrome: stable
before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - export CHROME_BIN=chromium-browser
